Flags improvements
Incendo/cloud pull request #127
Opened 2020-11-01 05:24 UTC by jmanpenilla

- Allow for use of named suggestion providers in `@Flag` annotated command method parameters
- Add methods to FlagContext to work with flag values as optionals

2020-11-01 07:16 UTC, Proximyst requested changes

2020-11-01 07:16 UTC, Proximyst commented on cloud-annotations/src/main/java/cloud/commandframework/annotations/Flag.java
> + *     <li>If the parameter is a {@code boolean} then a presence flag will be created</li>
```suggestion
 *     <li>If the parameter is a {@code boolean}, a presence flag will be created</li>
```
This isn't a programming language; "if then" sounds bad :(

2020-11-01 07:16 UTC, Proximyst commented on cloud-annotations/src/main/java/cloud/commandframework/annotations/Flag.java
> + *     will be resolved the same way as it would for an {@link Argument}</li>
```suggestion
 *     will resolve it the same way as it would for an {@link Argument}</li>
```

2020-11-01 07:16 UTC, Proximyst commented on cloud-annotations/src/main/java/cloud/commandframework/annotations/Flag.java
> +     * the {@link cloud.commandframework.arguments.parser.ParserRegistry} instance in the
Import the links. This is supposed to be easily readable, even outside the javadoc page.

2020-11-01 07:16 UTC, Proximyst commented on cloud-annotations/src/main/java/cloud/commandframework/annotations/FlagExtractor.java
> +                    argument = argumentBuilder.withSuggestionsProvider(suggestionProvider).build();
Would it be an idea to just have `withSuggestionsProvider` accept a `null` for default?

2020-11-01 07:16 UTC, Proximyst commented on cloud-core/src/main/java/cloud/commandframework/arguments/flags/FlagContext.java
> +     * Check whether or not a presence flag is present. This will return {@code false}
```suggestion
     * Check whether a presence flag is present. This will return {@code false}
```

2020-11-01 07:16 UTC, Proximyst commented on cloud-core/src/main/java/cloud/commandframework/arguments/parser/ParserRegistry.java
> +     * @return Optional that either contains the suggestion provider, or nothing ({@link Optional#empty()}) if no
```suggestion
     * @return Optional that either contains the suggestion provider, or empty if no
```
We just call the optional empty elsewhere in the code.

2020-11-01 07:16 UTC, Proximyst commented on cloud-annotations/src/main/java/cloud/commandframework/annotations/Flag.java
> +    String suggestions() default "";
I miss a nullability annotation here.

2020-11-12 00:45 UTC, Sauilitired approved these changes

2020-11-12 00:45 UTC, merged