Annotations API fix failure when a literal name matches an argument name
Incendo/cloud pull request #143
Opened 2020-11-22 02:31 UTC by bergerkiller

When registering a command such as this:
```java
    @CommandMethod("train ticket <ticket>")
    private void commandGiveTicket(
              final CommandSender sender,
              final @Argument("ticket") String ticketName
    ) {
    }
```

This caused a weird situation where the ticketName argument was bound to the first ticket literal, rather than the second. This broke some things when you had other literals defined on the same level. I tracked it down to how the syntax fragments are parsed, which used a LinkedHashMap. This is not correct, since literals can repeat as argument names. Quite common to do this.

This commit replaces that with a List<SyntaxFragment> and a simple lookup function which only looks for arguments, skipping literals entirely. Literals should never match with @Argument parameters of the method.

2020-11-22 20:26 UTC, Sauilitired approved these changes

2020-11-25 02:47 UTC, jmanpenilla requested changes
LGTM, just some minor codestyle things

2020-11-25 02:47 UTC, jmanpenilla commented on cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
> +                        findSyntaxFragment(tokens, argumentPair.getArgument().value()),
```suggestion
                        this.findSyntaxFragment(tokens, argumentPair.getArgument().value()),
```

2020-11-25 02:47 UTC, jmanpenilla commented on cloud-annotations/src/main/java/cloud/commandframework/annotations/AnnotationParser.java
> +    private @NonNull SyntaxFragment findSyntaxFragment(final @NonNull List<SyntaxFragment> fragments,
```diff
-     private @NonNull SyntaxFragment findSyntaxFragment(final @NonNull List<SyntaxFragment> fragments,
-                                                        final @NonNull String argumentName
+     private @NonNull SyntaxFragment findSyntaxFragment(
+             final @NonNull List<SyntaxFragment> fragments,
+             final @NonNull String argumentName
+     ) {
```

2020-11-25 09:17 UTC, bergerkiller commented
I'm a little new to github's auto-resolving feature. If I use the 'resolve conversation' button, does that add new commits to my repository with your suggested changes, only to this PR, or something else altogether? Ideally I keep all changes inside a single commit, but I could squash it later.

2020-11-25 09:20 UTC, Proximyst commented
Resolving just collapses the comment for everyone.

2020-11-25 09:32 UTC, bergerkiller commented
Ah, so commit suggestion button makes the new commit most likely. Does that commit to my own (bergerhealer) repo?

2020-11-25 11:29 UTC, Sauilitired commented
> Ah, so commit suggestion button makes the new commit most likely. Does that commit to my own (bergerhealer) repo?

it makes a commit to the source branch, which in this case is in your repository

2020-11-25 17:11 UTC, bergerkiller commented
Applied the requested changes

2020-11-25 21:28 UTC, jmanpenilla approved these changes

2020-11-29 14:31 UTC, merged