Allow a custom CaptionVariableReplacementHandler
Incendo/cloud pull request #352
Opened 2022-04-13 15:17 UTC by 0utplay

This PR adds getter and setter to the CommandManager,
making it possible to set the CaptionVariableReplacementHandler ourself.

2022-04-13 19:36 UTC, jpenilla requested changes
Needs to update changelog

2022-04-13 19:36 UTC, jpenilla commented on cloud-core/src/main/java/cloud/commandframework/CommandManager.java
> +            @NonNull final CaptionVariableReplacementHandler captionVariableReplacementHandler
`final @NonNull`

2022-04-13 19:36 UTC, jpenilla commented on cloud-core/src/main/java/cloud/commandframework/CommandManager.java
> +    public void setCaptionVariableReplacementHandler(
no set prefix

2022-04-13 19:36 UTC, jpenilla commented on cloud-core/src/main/java/cloud/commandframework/CommandManager.java
> +    public @NonNull CaptionVariableReplacementHandler getCaptionVariableReplacementHandler() {
no get prefix

2022-04-13 19:36 UTC, jpenilla commented on cloud-core/src/main/java/cloud/commandframework/CommandManager.java
> +     * Set the caption variable replacement handler
```suggestion
     * Sets the caption variable replacement handler.
```

2022-04-14 18:26 UTC, jpenilla requested changes

2022-04-14 18:26 UTC, jpenilla commented on CHANGELOG.md
> +### Changed
```suggestion
### Added
```

2022-04-14 18:26 UTC, jpenilla commented on CHANGELOG.md
> +- The command manager specifies the caption replacement handler
```suggestion
- Allow for setting a custom `CaptionVariableReplacementHandler` on the command manager ([#352](https://github.com/Incendo/cloud/pull/352))
```

2022-04-19 17:19 UTC, 0utplay commented
Hey, is something wrong with the PR or not up to your standards?

2022-05-21 07:53 UTC, Citymonstret commented
I think this is a sensible contribution. It has some merge conflicts that would currently prevent it from being merged. But I don't have any objections to this being added to v1.7.

2022-05-26 09:14 UTC, Citymonstret approved these changes

2022-05-26 09:18 UTC, merged