Allow greedy parsers to suggest after a space
Incendo/cloud pull request #414
Opened 2022-12-10 23:59 UTC by Pablete1234

Fixes #190

2022-12-11 00:20 UTC, jpenilla requested changes

2022-12-11 00:20 UTC, jpenilla commented on cloud-core/src/main/java/cloud/commandframework/CommandTree.java
> +            String input = commandQueue.size() == 1 ? commandQueue.peek()
please make this final, and imo the double ternary is still readable but it might be better to have one of them be an if to make things more obvious

2022-12-11 00:43 UTC, jpenilla approved these changes

2022-12-13 06:47 UTC, Citymonstret approved these changes

2022-12-13 16:19 UTC, merged