Add command context type lookup methods
Incendo/cloud pull request #422
Opened 2022-12-13 23:08 UTC by jpenilla

Things to consider:
- Do we want a custom result type instead of `Pair`/`Collection<Pair>`?
- Overloads with default values for the two booleans

2022-12-14 07:13 UTC, zml2008 commented
What was your idea of a use case on this? (i also only see one boolean?)

2022-12-14 17:10 UTC, broccolai commented
Not sure about this, the implementation looks good but I'm not sure we should be encouraging this kind of abuse with the command context.

2022-12-15 10:47 UTC, Citymonstret requested changes
(As mentioned in Discord) I'd like to see the main signatures with TypeToken and have the existing signatures delegate to those, as CloudKey is TypeToken based. It'd be neat to compare those directly, rather than getting the underlying class

2022-12-15 10:47 UTC, Citymonstret commented on cloud-core/src/main/java/cloud/commandframework/context/CommandContext.java
> +     * <p>When {@code exactType} is {@code flase}, a value may be returned
```suggestion
     * <p>When {@code exactType} is {@code false}, a value may be returned
```

2022-12-15 10:47 UTC, Citymonstret commented on cloud-core/src/main/java/cloud/commandframework/context/CommandContext.java
> +     * if it's type is assignable to {@code type}. Otherwise the type must pass
```suggestion
     * if its type is assignable to {@code type}. Otherwise the type must pass
```

2024-01-15 04:56 UTC, jpenilla commented
I don't think this is something we want, injectors can be used for this purpose.

2024-01-15 04:56 UTC, closed without merging