Allow PredicatePermissions to return a PermissionResult
Incendo/cloud pull request #545
Opened 2023-12-05 09:50 UTC by Konicai

A few things:
- Will add a better PR description tomorrow, probably
- Will javadoc and fix checkstyle issues tomorrow, probably
- It seems like `AndPermission` and `OrPermission` had loose definitions of what to do when empty. `OrPermission` already resulted in false, but I added a check for `AndPermission` so that it now also results in false. I was thinking of requiring a non-empty Set in their constructors, and also moving the iteration to the respective classes. Can't move much more up without introducing a generic to CommandPermission, which seems yucky.
- I was originally going to make `PermissionLevelResult` with a private constructor and a static factory method. But then I figured that it wouldn't hurt to allow the class to be extended. So then I was looking at a protected constructor and a static factory method, and I figured to just have a public constructor. It feels like I'm getting bureaucratic. Maybe a middle ground?

2023-12-05 09:55 UTC, Konicai commented on cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/FabricClientCommandManager.java
> +        );    }
oop

2023-12-06 14:01 UTC, powercasgamer requested changes

2023-12-06 17:30 UTC, jpenilla commented
as mentioned on discord, the result for an empty and permission shouldn't be changed. but requiring a non empty set also sounds reasonable.

2023-12-10 03:56 UTC, Konicai commented
thank you - got busy the last couple days. I'll be able to finish this today or tomorrow

2023-12-10 06:17 UTC, Citymonstret commented
> thank you - got busy the last couple days. I'll be able to finish this today or tomorrow

absolutely no rush, I just figured I'd help keep it up to date with 2.0.0-dev as it's still moving quite fast :sweat_smile:

2023-12-17 04:24 UTC, Konicai commented
@jpenilla can i get some guidance/clarification on the direction i should take with AndPermission/OrPermission :)

2023-12-20 06:55 UTC, Citymonstret commented
I merged in the changes from #578, hopefully I didn't butcher it too badly.

2024-01-13 08:25 UTC, Citymonstret approved these changes

2024-01-13 22:13 UTC, Citymonstret approved these changes

2024-01-13 22:18 UTC, Konicai commented
thank you... a bit taken by life right now 😆

2024-01-14 00:57 UTC, jpenilla approved these changes

2024-01-14 01:03 UTC, merged